export type BrandAssetStatus = "primary" | "secondary" | "legacy";

export interface BrandAssetBundle {
  slug: string;
  displayName: string;
  aliases: readonly string[];
  status: BrandAssetStatus;
  logo: string;
  heroImage?: string;
  galleryImages: readonly string[];
  sourceUrls: readonly string[];
  notes: string;
}

export const brandAssetBundles = [
  {
    slug: "helix",
    displayName: "Helix",
    aliases: ["Helix Sleep"],
    status: "primary",
    logo: "/brand-assets/helix/logo.png",
    heroImage: "/brand-assets/helix/hero.webp",
    galleryImages: [
      "/brand-assets/helix/lifestyle.jpg",
      "/brand-assets/helix/awards.png",
    ],
    sourceUrls: [
      "https://www.discountmattressbg.com/",
      "https://www.discountmattressbg.com/helix-brand-page",
    ],
    notes: "Strong current Discount Mattress logo and Helix brand-page media. Hero works best as a supporting banner or editorial image.",
  },
  {
    slug: "puffy",
    displayName: "Puffy",
    aliases: ["Puffy Mattress"],
    status: "primary",
    logo: "/brand-assets/puffy/logo.png",
    heroImage: "/product-assets/puffy-refresh/monarch-hero-wide.webp",
    galleryImages: [
      "/brand-assets/puffy/brand-wordmark.png",
      "/brand-assets/puffy-refresh/monarch-card.png",
      "/brand-assets/puffy-refresh/lux-card.png",
      "/brand-assets/puffy-refresh/royal-card.png",
      "/brand-assets/puffy-refresh/cloud-card.png",
      "/product-assets/puffy-refresh/monarch-crop-01.webp",
    ],
    sourceUrls: [
      "https://www.discountmattressbg.com/",
      "https://www.discountmattressbg.com/puffy-brand-page",
      "https://puffy.com/products/puffy-mattress",
      "https://puffy.com/products/puffy-lux-mattress",
      "https://puffy.com/products/puffy-royal-mattress",
      "https://puffy.com/products/puffy-monarch-mattress",
    ],
    notes: "Refreshed with current official Puffy product and gallery images for cleaner collection and product-page presentation.",
  },
  {
    slug: "dreamcloud",
    displayName: "DreamCloud",
    aliases: ["Dream Cloud"],
    status: "primary",
    logo: "/brand-assets/dreamcloud/logo.png",
    heroImage: "/brand-assets/dreamcloud/classic-product.webp",
    galleryImages: ["/brand-assets/dreamcloud/comparison.png"],
    sourceUrls: [
      "https://www.discountmattressbg.com/",
      "https://www.discountmattressbg.com/dream-cloud-brand-page",
    ],
    notes: "Good logo and product media, with a comparison asset useful for content sections.",
  },
  {
    slug: "nectar",
    displayName: "Nectar",
    aliases: ["Nectar Sleep"],
    status: "primary",
    logo: "/brand-assets/nectar/logo.png",
    heroImage: "/brand-assets/nectar/tile-clean.jpg",
    galleryImages: [
      "/brand-assets/nectar/dark-wordmark.png",
      "/brand-assets/nectar/feature-01.jpg",
      "/brand-assets/nectar/feature-02.jpg",
      "/brand-assets/nectar/feature-03.jpg",
      "/brand-assets/nectar/feature-04.jpg",
      "/product-assets/nectar-refresh/classic-hybrid.png",
      "/product-assets/nectar-refresh/premier-hybrid.png",
      "/product-assets/nectar-refresh/luxe-memory.png",
      "/product-assets/nectar-refresh/ultra-hybrid.png",
    ],
    sourceUrls: [
      "https://www.discountmattressbg.com/",
      "https://www.discountmattressbg.com/nectar-brand-page",
    ],
    notes: "Good logo, product, and feature art from the active Nectar Discount Mattress page.",
  },
  {
    slug: "bedgear",
    displayName: "Bedgear",
    aliases: ["BEDGEAR"],
    status: "primary",
    logo: "/brand-assets/bedgear/logo.png",
    heroImage: "/brand-assets/bedgear/m3-hero.webp",
    galleryImages: [
      "/brand-assets/bedgear/m3-main.webp",
      "/brand-assets/bedgear/m3-angle.webp",
      "/brand-assets/bedgear/m3-comfort-units.webp",
      "/brand-assets/bedgear/m3-airflow.webp",
      "/brand-assets/bedgear/m3-comfort-range.webp",
      "/brand-assets/bedgear/m3-split-head.webp",
      "/brand-assets/bedgear/m5-main.webp",
      "/brand-assets/bedgear/m5-lifestyle.webp",
      "/brand-assets/bedgear/m5-comfort-units.webp",
      "/brand-assets/bedgear/m5-airflow.webp",
      "/brand-assets/bedgear/m5-detail.webp",
      "/brand-assets/bedgear/storm-performance.webp",
      "/brand-assets/bedgear/balance-performance.webp",
    ],
    sourceUrls: [
      "https://www.discountmattressbg.com/",
      "https://www.discountmattressbg.com/bedgear-brand-page",
    ],
    notes: "Strong hero and M3 product media for a polished performance-mattress collection page.",
  },
  {
    slug: "naturepedic",
    displayName: "Naturepedic",
    aliases: ["NaturePedic", "Naturepedic EOS"],
    status: "primary",
    logo: "/brand-assets/naturepedic/discount-logo.jpg",
    heroImage: "/brand-assets/naturepedic/tile-clean.jpg",
    galleryImages: [
      "/brand-assets/naturepedic/eos-classic.webp",
      "/brand-assets/naturepedic/eos-detail.webp",
      "/brand-assets/naturepedic/showroom.jpeg",
      "/brand-assets/naturepedic/lifestyle.jpg",
    ],
    sourceUrls: [
      "https://www.discountmattressbg.com/",
      "https://www.discountmattressbg.com/naturepedic-brand-page-eos-classic",
    ],
    notes: "Good EOS and showroom imagery; logo is usable but should be replaced with a higher-resolution official transparent logo if one is licensed later.",
  },
  {
    slug: "posh-and-lavish",
    displayName: "Posh and Lavish",
    aliases: ["Posh+Lavish", "Posh & Lavish"],
    status: "primary",
    logo: "/brand-assets/posh-and-lavish/discount-logo.png",
    heroImage: "/brand-assets/posh-and-lavish/official-hero.avif",
    galleryImages: [
      "/brand-assets/posh-and-lavish/dm-hero.webp",
      "/brand-assets/posh-and-lavish/dm-product.webp",
      "/brand-assets/posh-and-lavish/providence-detail.png",
      "/brand-assets/posh-and-lavish/rubber-tree.jpg",
      "/brand-assets/posh-and-lavish/official-logo-white.svg",
      "/brand-assets/posh-and-lavish/official-craftsmanship.jpg",
      "/brand-assets/posh-and-lavish/official-front-01.avif",
      "/brand-assets/posh-and-lavish/official-front-02.avif",
    ],
    sourceUrls: [
      "https://www.discountmattressbg.com/",
      "https://www.discountmattressbg.com/posh-and-lavish-brand-page",
      "https://www.discountmattressbg.com/posh-and-lavish-providence-3-inch-true-pillow-top-product-page",
      "https://www.poshandlavish.com/",
    ],
    notes: "Deepest premium visual set: Discount Mattress page assets plus current official Posh+Lavish lifestyle/product imagery.",
  },
  {
    slug: "pranasleep",
    displayName: "PranaSleep",
    aliases: ["Prana Sleep", "PranaSleep Karma"],
    status: "primary",
    logo: "/brand-assets/pranasleep/logo.png",
    heroImage: "/brand-assets/pranasleep/tile-clean.jpg",
    galleryImages: [
      "/brand-assets/pranasleep/karma-elite.webp",
      "/brand-assets/pranasleep/showroom.jpeg",
      "/brand-assets/pranasleep/product-01.avif",
      "/brand-assets/pranasleep/product-02.avif",
    ],
    sourceUrls: [
      "https://www.discountmattressbg.com/",
      "https://www.discountmattressbg.com/pranasleep-karma-collection",
    ],
    notes: "Strong page-ready set for Karma-focused collection content.",
  },
  {
    slug: "bedtech",
    displayName: "BedTech",
    aliases: ["Bed Tech"],
    status: "primary",
    logo: "/brand-assets/bedtech/logo.png",
    heroImage: "/brand-assets/bedtech/official-hero-bases.jpg",
    galleryImages: [
      "/brand-assets/bedtech/discount-logo.png",
      "/brand-assets/bedtech/official-hybrid.jpg",
      "/brand-assets/bedtech/official-lifestyle.jpg",
      "/brand-assets/bedtech/btx4-base.webp",
      "/brand-assets/bedtech/bt2000.webp",
      "/brand-assets/bedtech/bt3000.webp",
      "/brand-assets/bedtech/bt6500.webp",
    ],
    sourceUrls: [
      "https://www.discountmattressbg.com/",
      "https://www.discountmattressbg.com/bed-tech-adjustable-bases",
      "https://www.bedtech.com/",
      "https://www.bedtech.com/collections/bases",
    ],
    notes: "Strong mix of official BedTech lifestyle/base images and Discount Mattress model-specific images.",
  },
  {
    slug: "serenity-sleep",
    displayName: "Serenity Sleep",
    aliases: ["Serenity Sleep Products"],
    status: "secondary",
    logo: "/brand-assets/serenity-sleep/logo.png",
    heroImage: "/brand-assets/serenity-sleep/hero.jpeg",
    galleryImages: [
      "/brand-assets/serenity-sleep/discount-logo.jpg",
      "/brand-assets/serenity-sleep/family.jpg",
      "/brand-assets/serenity-sleep/alpine-plush.png",
      "/brand-assets/serenity-sleep/andes-euro-top.png",
      "/brand-assets/serenity-sleep/sonora-hybrid.png",
    ],
    sourceUrls: [
      "https://www.discountmattressbg.com/",
      "https://yourbestrest.com/",
      "https://yourbestrest.com/about/",
    ],
    notes: "Discount Mattress has a small logo; official Serenity Sleep Products media fills in product and lifestyle depth.",
  },
  {
    slug: "jamison",
    displayName: "Jamison",
    aliases: ["Jamison Bedding"],
    status: "secondary",
    logo: "/brand-assets/jamison/logo.png",
    heroImage: "/brand-assets/jamison/hero.png",
    galleryImages: [
      "/brand-assets/jamison/discount-logo.png",
      "/brand-assets/jamison/hotel-bed.png",
      "/brand-assets/jamison/hotel-bed-03.png",
      "/brand-assets/jamison/innerspring-hotel.png",
      "/brand-assets/jamison/family-comfort.png",
    ],
    sourceUrls: [
      "https://www.discountmattressbg.com/",
      "https://www.jamisonbedding.com/",
      "https://www.jamisonbedding.com/about",
    ],
    notes: "Official Jamison assets are high-quality and collection-ready; current Discount Mattress source only had a small logo.",
  },
  {
    slug: "serta",
    displayName: "Serta",
    aliases: ["Serta Mattress"],
    status: "secondary",
    logo: "/brand-assets/serta/logo.svg",
    heroImage: "/brand-assets/serta/icomfort-preview.jpg",
    galleryImages: [
      "/brand-assets/serta/discount-logo.png",
      "/brand-assets/serta/sheep-lifestyle.jpg",
      "/brand-assets/serta/icomfort-preview.jpg",
    ],
    sourceUrls: [
      "https://www.discountmattressbg.com/",
      "https://www.serta.com/",
      "https://www.serta.com/mattresses/icomfort",
    ],
    notes: "Uses official Serta logo and brand imagery, plus the existing Discount Mattress Serta logo.",
  },
  {
    slug: "corsicana",
    displayName: "Corsicana",
    aliases: ["Corsicana Mattress"],
    status: "legacy",
    logo: "/brand-assets/corsicana/logo.svg",
    heroImage: "/brand-assets/corsicana/tile.jpg",
    galleryImages: [
      "/brand-assets/corsicana/wordmark.png",
      "/brand-assets/corsicana/lifestyle.jpg",
      "/brand-assets/corsicana/factory.jpg",
      "/brand-assets/corsicana/about-01.png",
      "/brand-assets/corsicana/about-02.png",
    ],
    sourceUrls: [
      "https://www.corsicanamattress.com/",
      "https://www.corsicanamattress.com/pages/about-us",
    ],
    notes: "Legacy/catalog brand candidate with a strong official logo and current Corsicana corporate/product media.",
  },
  {
    slug: "malouf",
    displayName: "Malouf",
    aliases: ["Malouf Home"],
    status: "legacy",
    logo: "/brand-assets/malouf/logo.png",
    heroImage: "/brand-assets/malouf/hero.jpg",
    galleryImages: [
      "/brand-assets/malouf/cooling-pillows.jpg",
      "/brand-assets/malouf/polaris.jpg",
      "/brand-assets/malouf/bedding-hero.jpg",
      "/brand-assets/malouf/protector.jpg",
    ],
    sourceUrls: [
      "https://www.maloufhome.com/",
      "https://www.maloufhome.com/collections/bedding",
    ],
    notes: "Legacy/catalog accessory brand candidate with strong current official product and bedding media.",
  },
  {
    slug: "icomfort",
    displayName: "iComfort",
    aliases: ["Serta iComfort", "iComfort by Serta"],
    status: "legacy",
    logo: "/brand-assets/icomfort/serta-logo.svg",
    heroImage: "/brand-assets/icomfort/hero-medium.jpg",
    galleryImages: [
      "/brand-assets/icomfort/hero-plush.jpg",
      "/brand-assets/icomfort/hero-firm.jpg",
      "/brand-assets/icomfort/btf-square-a.jpg",
      "/brand-assets/icomfort/btf-square-b.jpg",
    ],
    sourceUrls: ["https://www.serta.com/mattresses/icomfort"],
    notes: "Treat as a Serta collection rather than a standalone manufacturer. Official iComfort product imagery is strong.",
  },
  {
    slug: "serta-sleep-retreat",
    displayName: "Serta Sleep Retreat",
    aliases: ["Sleep Retreat", "Sleep Retreat by Serta"],
    status: "legacy",
    logo: "/brand-assets/serta-sleep-retreat/serta-logo.svg",
    heroImage: "/brand-assets/serta-sleep-retreat/sugar-beach-01.jpg",
    galleryImages: [
      "/brand-assets/serta-sleep-retreat/sugar-beach-02.jpg",
      "/brand-assets/serta-sleep-retreat/sugar-beach-03.jpg",
      "/brand-assets/serta-sleep-retreat/pearl-beach.jpg",
    ],
    sourceUrls: [
      "https://www.hobbsfurn.com/products/Serta/ser/500957742queen.html",
      "https://www.novellofurniture.com/item/sleep-retreat-full-innerspring-mattress-set/87179750",
    ],
    notes: "Older Serta collection with retailer-sourced media. Keep as legacy until confirmed as currently sold by Discount Mattress.",
  },
] as const satisfies readonly BrandAssetBundle[];

export const brandAssetsBySlug = Object.fromEntries(
  brandAssetBundles.map((bundle) => [bundle.slug, bundle]),
) as Record<(typeof brandAssetBundles)[number]["slug"], (typeof brandAssetBundles)[number]>;

export function getBrandAssetBundle(slug: string) {
  return brandAssetBundles.find((bundle) => bundle.slug === slug);
}
