name: Deploy Shopify Theme
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install and push
        env:
          SHOPIFY_CLI_PASSWORD: ${{ secrets.SHOPIFY_CLI_PASSWORD }}
        run: |
          npm install -g @shopify/cli
          which shopify
          shopify --version
          echo "Env: SHOPIFY_CLI_PASSWORD is set to [${SHOPIFY_CLI_PASSWORD:0:8}]..."
          shopify theme push \
            --store discount-mattress-4.myshopify.com \
            --theme ${{ secrets.SHOPIFY_LIVE_THEME_ID }} \
            --allow-live
